[package]
name = "rexdna"
version = "0.0.1"
authors = ["CryptoPatrick <cryptopatrick@gmail.com>"]
edition = "2018"
description = "Regular Expressions optimized for DNA."
documentation = "https://docs.rs/rexdna"
homepage = "https://github.com/cryptopatrick/rexdna"
repository = "https://github.com/cryptopatrick/rexdna"
readme = "README.md"
keywords = ["dna", "regexp", "regular expressions", "utility"]
license = "Unlicense/MIT"
autotests = false

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
