[package]
name = "sbe"
version = "0.0.1"
authors = ["cryptopatrick <cryptopatrick@gmail.com>"]
edition = "2018"
description = "Simple Binary Encoding (SBE)"
documentation = "https://docs.rs/sbe"
homepage = "https://github.com/cryptopatrick/sbe"
repository = "https://github.com/cryptopatrick/sbe"
readme = "README.md"
keywords = ["sbe", "binary", "encoding", "messaging", "fix"]
license = "Unlicense/MIT"
autotests = false

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
